// GMsg_All.h  -*- C++ -*-
// $Id: GMsg_All.h,v 1.24 1998-04-24 16:18:04-07 jason Exp $
// Copyright 1996-1997 Lyra LLC, All rights reserved. 
//
// Include all GMsg*.h files

#ifndef INCLUDED_GMsg_All
#define INCLUDED_GMsg_All

#include "GMsg.h"

#include "GMsg_AgentLogin.h"
#include "GMsg_ChangeAvatar.h"
#include "GMsg_ChangeStat.h"
#include "GMsg_CreateItem.h"
#include "GMsg_DestroyItem.h"
#include "GMsg_DestroyRoomItem.h"
#include "GMsg_Error.h"
#include "GMsg_GetGoalHdrs.h"
#include "GMsg_GetItem.h"
#include "GMsg_GetItemDescription.h"
#include "GMsg_GetLevelPlayers.h"
#include "GMsg_GetPlayerName.h"
#include "GMsg_GetReportHdrs.h"
#include "GMsg_GiveItem.h"
#include "GMsg_GiveItemAck.h"
#include "GMsg_Goal.h"
#include "GMsg_GotoLevel.h"
#include "GMsg_GrantPPoint.h"
#include "GMsg_ItemDescription.h"
#include "GMsg_ItemDrop.h"
#include "GMsg_ItemPickup.h"
#include "GMsg_LevelPlayers.h"
#include "GMsg_LocateAvatar.h"
#include "GMsg_LocateAvatarAck.h"
#include "GMsg_LocateMaresAck.h"
#include "GMsg_LocateNewliesAck.h"
#include "GMsg_Login.h"
#include "GMsg_LoginAck.h"
#include "GMsg_Logout.h"
#include "GMsg_Ping.h"
#include "GMsg_PostGoal.h"
#include "GMsg_PostReport.h"
#include "GMsg_PPointAck.h"
#include "GMsg_PreLogin.h"
#include "GMsg_PreLoginAck.h"
#include "GMsg_PutItem.h"
#include "GMsg_RcvGoalbookHdr.h"
#include "GMsg_RcvGoalDetails.h"
#include "GMsg_RcvGoalHdr.h"
#include "GMsg_RcvGoalText.h"
#include "GMsg_RcvPlayerName.h"
#include "GMsg_RcvReportHdr.h"
#include "GMsg_RcvReportGoals.h"
#include "GMsg_RcvReportText.h"
#include "GMsg_ServerDown.h"
#include "GMsg_SetAvatarDescription.h"
#include "GMsg_SenseDreamersAck.h"
#include "GMsg_ShowItem.h"
#include "GMsg_TakeItem.h"
#include "GMsg_TakeItemAck.h"
#include "GMsg_UpdateItem.h"
#include "GMsg_UpdateStats.h"
#include "GMsg_UsePPoint.h"
#include "GMsg_ViewItem.h"

#endif /* INCLUDED_GMsg_All */
